def app = "maven-code-coverage"  // This variable is global
node('small') {
    stage('Stage1') { // for display purposes
        def app2 = "another-app"
        sh "echo ${app} "
        sh "echo ${app2} "
        app = "my-new-app"
        app2 = "my-new-app"
        sh "echo ${app} "
        sh "echo ${app2} "
    }
}
node('large') {

    stage('Stage2') {
        sh "echo ${app} "
        sh "echo ${app2} "
    }
}
